### ISSUE TITLE
Правки по ДЗ

### ISSUE THREAD

**Issue by myroslav-kolomiiets** [Yevgeniy-Davydov/JS-HW1#2]
https://github.com/Yevgeniy-Davydov/JS-HW1/blob/d637c6c53b1e05f0fd69ba09dcee48aee066b779/index.js#L12
Ця змінна не потрібна, можна скоротити до return innerArr.join('.') + ".";

https://github.com/Yevgeniy-Davydov/JS-HW1/blob/d637c6c53b1e05f0fd69ba09dcee48aee066b779/index.js#L28C1-L28C1

Також можна скоротити до
const filteredNames = userNames.filter((name)=>{
    return letters.includes(name[0]);
});

https://github.com/Yevgeniy-Davydov/JS-HW1/blob/d637c6c53b1e05f0fd69ba09dcee48aee066b779/index.js#L40
купа лишніх змінних, такого бути не повинно, не треба створювати те що ніде більше не перевикористовується, все це можна звести до:
let reverseValue = Number(String(currentMaxValue).split('').reverse().join(''));

**Comment by Yevgeniy-Davydov** [comment]
я все просмотрел и исправил. спасибо за фидбэк!
